name: Build and Deploy Sphinx Docs

on:
  push:
    branches:
      - main
      - documentation
  pull_request:
    branches:
      - '*'

permissions:
  contents: write

jobs:
  build-docs:
    name: ${{ github.event_name == 'pull_request' && 'Check Build Docs' || 'Build Docs' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.11'
          cache: "pip"
      
      - name: Install Sphinx and extensions
        run: |
          python -m pip install --upgrade pip
          pip install myst-nb sphinx-autoapi sphinx nbsphinx sphinx-rtd-theme

      - name: Build HTML
        run: |
          cd docs
          make html

      - name: Upload Docs Artifact
        if: github.event_name == 'pull_request' || (github.event_name == 'push' && (github.ref == 'refs/heads/main'))
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/build/html

  deploy-docs:
    name: Deploy Docs
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    needs: build-docs
    steps:
      - uses: actions/checkout@v4
      
      - name: Download Docs Artifact
        uses: actions/download-artifact@v4
        with:
          name: documentation
          path: deploy

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
